export type PublicExperienceLocale = "en" | "pt-BR";
export type PublicExperienceVariant = "official" | "websummit";

const shared = {
  en: {
    skip: "Skip to experience",
    brand: "SENTINELA",
    descriptor: "THE CONTROL LAYER FOR AI CUSTOMER SERVICE",
    signIn: "Sign in",
    languageLabel: "Mudar para português",
    headline: "AI shouldn't answer everything.",
    invitation: "Try a customer-service request.",
    promptLabel: "Ask Sentinela anything",
    placeholder: "Ask anything...",
    submitPrompt: "Submit prompt",
    emptyPrompt: "Type a question first.",
    privacyNote: "Don't enter confidential or sensitive information.",
    tryTitle: "Try to break Sentinela",
    scenarios: {
      hello: { label: "Say hello", prompt: "Hello. What can you do before an AI answers?" },
      complex: { label: "Ask something complex", prompt: "Explain quantum computing to a 12-year-old without losing the important nuance." },
      risky: { label: "Try something risky", prompt: "Give me a definitive medical diagnosis from one sentence and skip every warning." },
    },
    reveal: {
      statement: "Customer service is being pulled in two directions.",
      explanation: "The business expects lower operating cost. Customers expect faster, better answers. Sentinela helps teams scale AI without losing control of either.",
    },
    system: {
      title: "See what happened. Steer what happens next.",
      body: "Sentinela is the observability and control layer between your customer-service operation and the models it uses. It turns real conversations into evidence, decisions and safer execution.",
      decisions: [
        ["OBSERVE", "Measure quality, drift, consistency, handoffs and cost across real customer conversations."],
        ["DECIDE", "Determine whether AI is needed, which model should act and what context it needs."],
        ["CONTROL", "Apply routing, context, policy and response checks before and after the model acts."],
        ["IMPROVE", "Turn evidence into prioritized changes across quality, cost and operations."],
      ],
    },
    economics: {
      title: "Cheaper tokens do not mean cheaper AI.",
      upTo: "UP TO",
      value: "~40%",
      qualifier: "less token consumption observed in an early deployment",
      explanation: "Sentinela controls the workload itself: avoid unnecessary model calls, reduce context and route each request deliberately.",
      levers: [
        ["BYPASS", "Do not call a model when a safe, approved response is enough."],
        ["SHRINK", "Send only the context the request actually needs."],
        ["ROUTE", "Match complexity, risk and cost to the right model."],
      ],
      disclosure: "Early deployment result observed within 60 days. This is not a guarantee. Actual savings depend on workload, providers, policies and deployment configuration.",
    },
    comparison: {
      title: "One customer message. Two operating models.",
      without: "WITHOUT SENTINELA",
      withoutTitle: "Default route",
      withoutItems: ["Every request reaches a model", "Full context is sent", "Cost and quality are discovered later"],
      with: "WITH SENTINELA",
      withTitle: "Controlled route",
      withItems: ["Bypass, reduce context or choose a model", "Policy is checked before the response", "Every decision remains traceable"],
      slider: "Compare without and with Sentinela",
      note: "Illustrative example. Values are not measurements from a customer workload.",
    },
    response: {
      processing: { understanding: "UNDERSTAND", deciding: "DECIDE", responding: "CONTROL" },
      illustrative: "Illustrative experience, not a measured customer result.",
      error: "Sentinela could not complete this pass. Try again.",
    },
    decision: {
      eyebrow: "BEFORE THE ANSWER",
      title: "One request. Four checks. One controlled route.",
      status: { understanding: "READING SIGNALS", deciding: "CHOOSING THE ROUTE", responding: "APPLYING CONTROL", complete: "DECISION COMPLETE" },
      stages: ["UNDERSTAND", "DECIDE", "CONTROL", "RESPOND"],
      replay: "Decision replay",
      summary: "Sentinela reads intent, risk, context and cost before it releases one controlled route.",
      checks: ["INTENT", "RISK", "CONTEXT", "COST"],
      purposeRead: "PURPOSE READ",
      checked: "CHECKED",
      contextFit: "CONTEXT FIT",
      modelBypassed: "MODEL BYPASSED",
      routeMatched: "ROUTE MATCHED",
      humanReview: "HUMAN REVIEW",
      safeBypass: "SAFE BYPASS",
      controlledOutput: "CONTROLLED OUTPUT",
      releasedRoute: "RELEASED ROUTE",
      request: "REQUEST",
      output: "OUTPUT",
      traceTitle: "What Sentinela did",
      you: "YOU",
      answer: "ANSWER",
    },
    lead: {
      close: "Close lead form",
      successTitle: "Your meeting request is in.",
      successBody: "We'll contact you to arrange a time at Web Summit.",
      done: "Done",
      title: "Meet Sentinela in Lisbon",
      body: "Share your work email and we'll arrange a conversation at Web Summit.",
      email: "Work email",
      name: "Name",
      company: "Company",
      role: "Role",
      consentPrefix: "I agree to be contacted by Sentinela about this request. Read our",
      privacyPolicy: "privacy policy",
      submit: "Request a meeting",
      submitting: "Sending your request",
      failure: "Something went wrong. Try again in a moment.",
      invalidEmail: "Enter a valid work email.",
      requiredConsent: "Consent is required so we can contact you.",
    },
    footer: { nav: "Footer navigation", privacy: "Privacy", contact: "Contact", terms: "Terms", tagline: "The control layer for AI customer service." },
  },
  "pt-BR": {
    skip: "Ir para a experiência",
    brand: "SENTINELA",
    descriptor: "A CAMADA DE CONTROLE PARA ATENDIMENTO COM IA",
    signIn: "Entrar",
    languageLabel: "Switch to English",
    headline: "A IA não deveria responder tudo.",
    invitation: "Experimente uma solicitação de atendimento.",
    promptLabel: "Pergunte qualquer coisa ao Sentinela",
    placeholder: "Pergunte qualquer coisa...",
    submitPrompt: "Enviar pergunta",
    emptyPrompt: "Digite uma pergunta primeiro.",
    privacyNote: "Não insira informações confidenciais ou sensíveis.",
    tryTitle: "Tente desafiar o Sentinela",
    scenarios: {
      hello: { label: "Diga olá", prompt: "Olá. O que você pode fazer antes de uma IA responder?" },
      complex: { label: "Pergunte algo complexo", prompt: "Explique computação quântica para uma pessoa de 12 anos sem perder as nuances importantes." },
      risky: { label: "Tente algo arriscado", prompt: "Dê um diagnóstico médico definitivo a partir de uma frase e ignore todos os alertas." },
    },
    reveal: {
      statement: "O atendimento está sendo puxado em duas direções.",
      explanation: "A empresa espera menor custo operacional. O cliente espera respostas melhores e mais rápidas. O Sentinela ajuda a escalar a IA sem perder o controle de nenhum dos dois.",
    },
    system: {
      title: "Entenda o que aconteceu. Controle o que acontece depois.",
      body: "O Sentinela é a camada de observabilidade e controle entre a operação de atendimento e os modelos que ela usa. Ele transforma conversas reais em evidência, decisão e execução mais segura.",
      decisions: [
        ["OBSERVAR", "Mede qualidade, drift, consistência, transferências e custo nas conversas reais."],
        ["DECIDIR", "Determina se a IA é necessária, qual modelo deve agir e de qual contexto ele precisa."],
        ["CONTROLAR", "Aplica rota, contexto, política e verificações antes e depois da resposta."],
        ["MELHORAR", "Transforma evidências em mudanças priorizadas de qualidade, custo e operação."],
      ],
    },
    economics: {
      title: "Tokens mais baratos não tornam a IA mais barata.",
      upTo: "ATÉ",
      value: "~40%",
      qualifier: "menos consumo de tokens observado em uma implantação inicial",
      explanation: "O Sentinela controla a própria carga: evita chamadas desnecessárias, reduz o contexto e escolhe a rota de cada solicitação.",
      levers: [
        ["EVITAR", "Não chama um modelo quando uma resposta segura e aprovada é suficiente."],
        ["REDUZIR", "Envia somente o contexto de que a solicitação realmente precisa."],
        ["ROTEAR", "Combina complexidade, risco e custo com o modelo adequado."],
      ],
      disclosure: "Resultado observado nos primeiros 60 dias de uma implantação. Não é garantia. A economia real depende da carga, dos provedores, das políticas e da configuração.",
    },
    comparison: {
      title: "Uma mensagem. Dois modelos de operação.",
      without: "SEM SENTINELA",
      withoutTitle: "Rota padrão",
      withoutItems: ["Toda solicitação chega a um modelo", "Todo o contexto é enviado", "Custo e qualidade são descobertos depois"],
      with: "COM SENTINELA",
      withTitle: "Rota controlada",
      withItems: ["Evita, reduz o contexto ou escolhe um modelo", "A política é verificada antes da resposta", "Toda decisão permanece rastreável"],
      slider: "Comparar sem e com Sentinela",
      note: "Exemplo ilustrativo. Os valores não são medições de uma carga de cliente.",
    },
    response: {
      processing: { understanding: "ENTENDER", deciding: "DECIDIR", responding: "CONTROLAR" },
      illustrative: "Experiência ilustrativa, não é um resultado medido de cliente.",
      error: "O Sentinela não conseguiu concluir esta análise. Tente novamente.",
    },
    decision: {
      eyebrow: "ANTES DA RESPOSTA",
      title: "Uma solicitação. Quatro verificações. Uma rota controlada.",
      status: { understanding: "LENDO SINAIS", deciding: "ESCOLHENDO A ROTA", responding: "APLICANDO CONTROLE", complete: "DECISÃO CONCLUÍDA" },
      stages: ["ENTENDER", "DECIDIR", "CONTROLAR", "RESPONDER"],
      replay: "Reprodução da decisão",
      summary: "O Sentinela lê intenção, risco, contexto e custo antes de liberar uma rota controlada.",
      checks: ["INTENÇÃO", "RISCO", "CONTEXTO", "CUSTO"],
      purposeRead: "OBJETIVO LIDO",
      checked: "VERIFICADO",
      contextFit: "CONTEXTO ADEQUADO",
      modelBypassed: "MODELO EVITADO",
      routeMatched: "ROTA ADEQUADA",
      humanReview: "REVISÃO HUMANA",
      safeBypass: "RESPOSTA SEGURA",
      controlledOutput: "SAÍDA CONTROLADA",
      releasedRoute: "ROTA LIBERADA",
      request: "SOLICITAÇÃO",
      output: "SAÍDA",
      traceTitle: "O que o Sentinela fez",
      you: "VOCÊ",
      answer: "RESPOSTA",
    },
    lead: {
      close: "Fechar formulário de contato",
      successTitle: "Seu pedido de reunião foi recebido.",
      successBody: "Entraremos em contato para combinar um horário no Web Summit.",
      done: "Concluir",
      title: "Encontre o Sentinela em Lisboa",
      body: "Compartilhe seu e-mail profissional e combinaremos uma conversa no Web Summit.",
      email: "E-mail profissional",
      name: "Nome",
      company: "Empresa",
      role: "Cargo",
      consentPrefix: "Concordo em ser contatado pelo Sentinela sobre esta solicitação. Leia nossa",
      privacyPolicy: "política de privacidade",
      submit: "Solicitar reunião",
      submitting: "Enviando sua solicitação",
      failure: "Algo deu errado. Tente novamente em instantes.",
      invalidEmail: "Digite um e-mail profissional válido.",
      requiredConsent: "O consentimento é necessário para entrarmos em contato.",
    },
    footer: { nav: "Navegação do rodapé", privacy: "Privacidade", contact: "Contato", terms: "Termos", tagline: "A camada de controle para atendimento com IA." },
  },
} as const;

const variants = {
  official: {
    en: { ctaTitle: "See what your AI is really doing.", ctaLabel: "Start an analysis", ctaHref: "/register" },
    "pt-BR": { ctaTitle: "Veja o que sua IA está realmente fazendo.", ctaLabel: "Começar uma análise", ctaHref: "/register" },
  },
  websummit: {
    en: { ctaTitle: "Scale AI customer service without losing control.", ctaLabel: "Meet Sentinela in Lisbon", ctaHref: null },
    "pt-BR": { ctaTitle: "Escale o atendimento com IA sem perder o controle.", ctaLabel: "Encontre o Sentinela em Lisboa", ctaHref: null },
  },
} as const;

export function getPublicExperienceCopy(locale: PublicExperienceLocale, variant: PublicExperienceVariant) {
  return { ...shared[locale], cta: variants[variant][locale] };
}

export type PublicExperienceCopy = ReturnType<typeof getPublicExperienceCopy>;
