import type { AnalysisResult } from "@/lib/api";

export const demoAnalysis: AnalysisResult = {
  engine_version: "sentinela-demo-v1",
  consistency_score: 58,
  global_confidence: 84,
  risk_level: "high",
  n_conversations: 128,
  n_intents: 14,
  token_waste_estimate: 2340,
  cross_intent_similarity: 82,
  response_variance: 47,
  response_stability_score: 56,
  intent_coverage_score: 72,
  covered_intents: 10,
  total_intents: 14,
  min_samples_per_intent: 3,
  underrepresented_intents: ["refund_policy", "plan_change", "shipping_delay"],
  critical_alerts_count: 4,
  alerts: [
    {
      severity: "critical",
      intent: "refund_policy",
      title: "Cross-intent reuse detected",
      hint: "Different refund and billing questions are receiving nearly identical answers.",
      recommendation: "Split refund and billing prompts so each intent has a distinct response policy.",
    },
    {
      severity: "high",
      intent: "shipping_delay",
      title: "Very low consistency score",
      hint: "Responses vary too much for the same shipping-delay scenario.",
      recommendation: "Normalize the shipping-delay response template and escalation criteria.",
    },
    {
      severity: "high",
      intent: "cancel_subscription",
      title: "Behavioral issue detected",
      hint: "Cancellation answers sometimes avoid the requested action and push unrelated retention language.",
      recommendation: "Tighten cancellation instructions and make completion steps explicit.",
    },
    {
      severity: "warning",
      intent: "plan_change",
      title: "Behavioral issue detected",
      hint: "Plan-change responses are too verbose and repeat product copy.",
      recommendation: "Trim repetitive product language and keep plan-change guidance task-focused.",
    },
  ],
  intents: [
    {
      intent: "refund_policy",
      consistency_score: 42,
      response_stability_score: 42,
      response_variance: 58,
      n_conversations: 11,
      mean_assistant_chars: 620,
      std_assistant_chars: 188,
      severity: "critical",
    },
    {
      intent: "shipping_delay",
      consistency_score: 49,
      response_stability_score: 49,
      response_variance: 51,
      n_conversations: 14,
      mean_assistant_chars: 540,
      std_assistant_chars: 140,
      severity: "high",
    },
    {
      intent: "cancel_subscription",
      consistency_score: 55,
      response_stability_score: 55,
      response_variance: 45,
      n_conversations: 9,
      mean_assistant_chars: 488,
      std_assistant_chars: 104,
      severity: "high",
    },
    {
      intent: "plan_change",
      consistency_score: 61,
      response_stability_score: 61,
      response_variance: 39,
      n_conversations: 8,
      mean_assistant_chars: 452,
      std_assistant_chars: 96,
      severity: "warning",
    },
    {
      intent: "password_reset",
      consistency_score: 86,
      response_stability_score: 86,
      response_variance: 14,
      n_conversations: 16,
      mean_assistant_chars: 212,
      std_assistant_chars: 34,
      severity: "info",
    },
  ],
  analyzed_at: new Date("2026-03-14T15:30:00.000Z").toISOString(),
  analysis_id: "demo-analysis-001",
  analysis_run_id: "demo-run-001",
  _warnings: [],
  _cache_key: "demo-analysis",
  _meta: {
    engine_version: "sentinela-demo-v1",
    cross_threshold_effective: 0.82,
    cross_threshold_source: "demo",
    mode: "demo",
  },
};
